#!/usr/bin/env python3
# =============================================================================
# DEPRECATED (REQ-0150, 2026-07-13). NOT part of the pipeline. Do not extend it,
# do not copy from it, do not cite it as precedent.
#
# Bakeoff perf probe. Superseded by the timings in tools/art_route.py.
#
# The pipeline is now:
#   tools/art_route.py       the ONE route (FLUX.2 klein) and the ONE graph
#   tools/art_style.py       the ONE prompt/style layer (ratified art direction)
#   tools/gen_item_icons.py  item + unit icons (defs-driven)
#   tools/gen_monster_art.py monster illustrations
#   tools/gen_bpskin.py      backpack skins: generate -> GATE -> compose
#   tools/bpskin_compose.py  fill + welt -> skin, over any polyomino
# Kept only so old batches can be read back. See docs/llm_managed/*_pipeline.md.
# =============================================================================

"""REQ-0136 clean warm-perf probe.

The historical leg timings are NOT comparable across contenders and must not
be put in a decision table:

  - dsxl was (re)generated by seq7 on an EXCLUSIVE, quiet box -> 14.0 s warm,
    tight and trustworthy.
  - v9 and flux were generated while the box was OOM-thrashing, being
    OOM-killed, and sharing the GPU with a second unattended runner
    (req0135_watch_and_run). v9's samples scatter 26.1 - 487.6 s with no
    band -> contention noise, not signal.

flux's samples DO form a tight band (13 of 16 within 539-641 s) which the
2h20m leg wall-clock corroborates, so flux is probably real -- but "probably"
is not good enough for a number the user selects a checkpoint on.

So: re-measure warm s/image for every contender under identical, quiet
conditions. Discard image 1 of each leg (cold model load), report the rest.
Writes to a scratch dir; the judged candidate PNGs are never touched.
"""
import argparse
import json
import os
import statistics as st
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gen_item_icons as G          # noqa: E402
import req0136_bakeoff as B         # noqa: E402

REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, "content/batches/bakeoff-0136/perfprobe")


def vram_now():
    try:
        return int(subprocess.run(
            ["nvidia-smi", "--query-gpu=memory.used",
             "--format=csv,noheader,nounits"],
            capture_output=True, text=True, timeout=10
        ).stdout.split()[0])
    except Exception:
        return 0


def probe(contender, subject, seeds):
    c = B.CONTENDERS[contender]
    subj = B.load_subjects(REPO, [subject])[0]
    w, h = subj["gen_render"]["gen_px"]
    secs, vram_peak = [], 0
    for i, seed in enumerate(seeds):
        prefix = f"perfprobe_{contender}_{seed}"
        if c["kind"] == "sdxl":
            wf = B.wf_sdxl(c, subj["gen_prompt"], subj.get("gen_negative", ""),
                           w, h, seed, prefix)
        else:
            wf = B.wf_flux2(c, subj["gen_prompt"], w, h, seed, prefix)
        t0 = time.time()
        hist = G.wait_done(G.submit(wf), timeout_s=1800)
        dt = time.time() - t0
        vram_peak = max(vram_peak, vram_now())
        ok = bool(hist) and hist.get("status", {}).get("status_str") != "error"
        tag = "COLD" if i == 0 else "warm"
        print(f"  {contender} s{seed} {tag} {dt:7.1f}s ok={ok}", flush=True)
        if ok and i > 0:                     # image 1 pays the model load
            secs.append(dt)
    return {"contender": contender, "cold_load_s": None,
            "warm_samples_s": [round(x, 1) for x in secs],
            "warm_median_s": round(st.median(secs), 1) if secs else None,
            "warm_mean_s": round(sum(secs) / len(secs), 1) if secs else None,
            "vram_peak_mib": vram_peak,
            "steps": c.get("steps"), "cfg": c.get("cfg")}


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--contenders", default="v9,dsxl,flux")
    ap.add_argument("--subject", default="unit-elf")
    # seed 0 is the cold load and is discarded; 3 warm samples each.
    ap.add_argument("--seeds", default="9001,9002,9003,9004")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    seeds = [int(s) for s in args.seeds.split(",")]

    res = {}
    for c in args.contenders.split(","):
        print(f"== {c}", flush=True)
        res[c] = probe(c, args.subject, seeds)
        # unload between contenders so each pays its own honest cold load
        B.free_models()
        time.sleep(5)

    path = os.path.join(OUT, "perfprobe.json")
    json.dump({"subject": args.subject, "note":
               "identical quiet-box conditions; image 1 of each leg "
               "(cold model load) discarded; 1024x1024; RTX 2080 8GB",
               "results": res}, open(path, "w"), indent=2)
    print("\n" + f"{'leg':<6}{'warm median':>13}{'warm mean':>11}"
          f"{'VRAM MiB':>10}{'steps':>7}")
    for c, r in res.items():
        print(f"{c:<6}{r['warm_median_s'] or -1:>13}{r['warm_mean_s'] or -1:>11}"
              f"{r['vram_peak_mib']:>10}{r['steps']:>7}")
    print("\nwrote " + path)
