#!/usr/bin/env python3
"""REQ-0135 spike: build the numbered side-by-side gallery.

For every (subject, seed) pair generated by both routes, emits one numbered
row: route A raw / A matte 256 / A matte 64(+4x blowup) / B RGBA 256 /
B RGBA 64(+4x blowup), with coverage %, matte method (A only, parsed from the
generation log) and per-image wall time. Self-contained HTML, relative paths,
dark theme, checkerboard behind transparent images (item pipeline S6 style).

Usage:
  scratch_req0135_build_gallery.py BASE_DIR LD_DIR BASE_LOG LD_LOG OUT_DIR
"""
import os
import re
import shutil
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_item_icons as G  # noqa: E402  (alpha_coverage_fraction, RAW_CANDIDATE_RE)
from PIL import Image  # noqa: E402

base_dir, ld_dir, base_log, ld_log, out_dir = sys.argv[1:6]
img_dir = os.path.join(out_dir, "img")
os.makedirs(img_dir, exist_ok=True)

# --- parse logs -------------------------------------------------------------
# route A matte method:  "MATTE <file> method=<m> coverage=<c>%"
method_a = {}
for m in re.finditer(r"MATTE (\S+_alpha\.png) method=(\S+) coverage=([\d.]+)%",
                     open(base_log).read()):
    method_a[m.group(1)] = m.group(2)
# per-job wall time:  "DONE id=<id> c=<k> seed=<s> ... (<t>s)" (route A)
#                     "DONE id=<id> c=<k> seed=<s> coverage=... time=<t>s vram_peak=<v>MiB" (route B)
time_a, time_b, vram_b = {}, {}, {}
for m in re.finditer(r"DONE id=(\S+) c=(\d+) seed=(\d+) -> \S+ \(([\d.]+)s\)",
                     open(base_log).read()):
    time_a[(m.group(1), m.group(2), m.group(3))] = float(m.group(4))
for m in re.finditer(r"DONE id=(\S+) c=(\d+) seed=(\d+) coverage=[\d.]+% "
                     r"time=([\d.]+)s vram_peak=(\d+)MiB", open(ld_log).read()):
    key = (m.group(1), m.group(2), m.group(3))
    time_b[key] = float(m.group(4))
    vram_b[key] = int(m.group(5))

# --- collect pairs ----------------------------------------------------------
pairs = []
for f in sorted(os.listdir(base_dir)):
    mm = G.RAW_CANDIDATE_RE.match(f)
    if not mm:
        continue
    eid, k, seed = mm.group("id"), mm.group("k"), mm.group("seed")
    alpha = f"{eid}_c{k}_s{seed}_alpha.png"
    if os.path.exists(os.path.join(ld_dir, alpha)):
        pairs.append((eid, k, seed, f, alpha))

SUBJECT_ORDER = ["hilt", "blade", "dagger", "wing", "elf_bust"]
pairs.sort(key=lambda p: (SUBJECT_ORDER.index(p[0]) if p[0] in SUBJECT_ORDER else 99, p[2]))


def emit(src, name):
    shutil.copyfile(src, os.path.join(img_dir, name))


def emit_64(src, name):
    im = Image.open(src)
    im64 = im.resize((im.width // 4, im.height // 4), Image.LANCZOS)
    im64.save(os.path.join(img_dir, name))


rows = []
for i, (eid, k, seed, raw, alpha) in enumerate(pairs, start=1):
    a_raw, a_alpha = os.path.join(base_dir, raw), os.path.join(base_dir, alpha)
    b_alpha = os.path.join(ld_dir, alpha)
    n = f"{i:02d}_{eid}_s{seed}"
    emit(a_raw, f"{n}_a_raw.png")
    emit(a_alpha, f"{n}_a_256.png")
    emit_64(a_alpha, f"{n}_a_64.png")
    emit(b_alpha, f"{n}_b_256.png")
    emit_64(b_alpha, f"{n}_b_64.png")
    cov_a = G.alpha_coverage_fraction(a_alpha) * 100
    cov_b = G.alpha_coverage_fraction(b_alpha) * 100
    key = (eid, k, seed)
    rows.append(dict(
        i=i, eid=eid, seed=seed, n=n,
        cov_a=cov_a, cov_b=cov_b,
        meth_a=method_a.get(alpha, "?"),
        t_a=time_a.get(key), t_b=time_b.get(key), vram=vram_b.get(key),
        tall=Image.open(a_alpha).height > Image.open(a_alpha).width))

# --- html -------------------------------------------------------------------
CSS = """
body{background:#131820;color:#E9E3D3;font:14px/1.5 system-ui,sans-serif;margin:24px}
h1{font-size:20px;color:#C9A959} .sub{color:#A8A193;max-width:70em}
table{border-collapse:collapse;margin-top:16px}
td,th{border:1px solid #3D434C;padding:8px;text-align:center;vertical-align:top}
th{background:#28313E;color:#C9A959}
.num{font-size:18px;font-weight:700;color:#C9A959}
.cb{background:repeating-conic-gradient(#555 0 25%,#777 0 50%) 0 0/16px 16px;display:inline-block;line-height:0}
.px{image-rendering:pixelated}
.meta{color:#A8A193;font-size:12px;margin-top:4px}
.bad{color:#E25822}.ok{color:#9c6}
img{display:block}
"""


def cell(name, w, cls=""):
    return (f'<span class="cb"><img class="{cls}" src="img/{name}" width="{w}"></span>')


html = [f"<!doctype html><meta charset='utf-8'><title>REQ-0135 LayerDiffuse spike</title>"
        f"<style>{CSS}</style>",
        "<h1>REQ-0135 — LayerDiffuse matting spike (route A = rembg birefnet-general "
        "+ edge-key fallback / route B = LayerDiffuse latent transparency)</h1>",
        "<p class='sub'>Same checkpoint (JuggernautXL V9), same prompts, same seeds "
        "(101/202), same sampler settings (30 steps, cfg 6.5, dpmpp_2m/karras). "
        "Checkerboard = transparency. The 64&nbsp;px column is the board-cell "
        "render (G4 readability), shown 1:1 and blown up 4x nearest-neighbour so "
        "edges are inspectable. Verdict per NUMBER please (green/fix/cut), or one "
        "verdict for the whole spike.</p>",
        "<table><tr><th>#</th><th>subject / seed</th><th>A raw (gen)</th>"
        "<th>A matte 256</th><th>A matte 64 + 4x</th>"
        "<th>B LayerDiffuse 256</th><th>B 64 + 4x</th><th>numbers</th></tr>"]

for r in rows:
    w256 = 192 if r["tall"] else 256
    w64 = w256 // 4
    cls_a = "ok" if 2 <= r["cov_a"] <= 90 else "bad"
    cls_b = "ok" if 2 <= r["cov_b"] <= 90 else "bad"
    ta = f"{r['t_a']:.0f}s" if r["t_a"] else "—"
    tb = f"{r['t_b']:.0f}s" if r["t_b"] else "—"
    vr = f"{r['vram']}MiB" if r["vram"] else "—"
    html.append(
        f"<tr><td class='num'>{r['i']}</td>"
        f"<td>{r['eid']}<div class='meta'>seed {r['seed']}</div></td>"
        f"<td><img src='img/{r['n']}_a_raw.png' width='{w256}'></td>"
        f"<td>{cell(r['n'] + '_a_256.png', w256)}</td>"
        f"<td>{cell(r['n'] + '_a_64.png', w64)}<br><br>{cell(r['n'] + '_a_64.png', w256, 'px')}</td>"
        f"<td>{cell(r['n'] + '_b_256.png', w256)}</td>"
        f"<td>{cell(r['n'] + '_b_64.png', w64)}<br><br>{cell(r['n'] + '_b_64.png', w256, 'px')}</td>"
        f"<td class='meta'>A: <span class='{cls_a}'>{r['cov_a']:.1f}%</span> "
        f"({r['meth_a']}, {ta})<br>B: <span class='{cls_b}'>{r['cov_b']:.1f}%</span> "
        f"(latent, {tb}, peak {vr})</td></tr>")

html.append("</table>")
open(os.path.join(out_dir, "index.html"), "w").write("\n".join(html))
print(f"gallery: {out_dir}/index.html rows={len(rows)}")
